### ISSUE TITLE
How to leave the loop to exit the application

### ISSUE THREAD

**Issue by zoechi** [vorner/signal-hook#103]
```rust
for info in &mut signals {
  ...
}
```
This loop blocks. 
When all other threads have ended, the app still does not exit because of this loop.
If I call `std::process::exit(0)` for force exit the app, termion destructors are not executed and the terminal is not properly reset (mouse drag causes Esc codes to be printed until I press <kbd>Ctrl</kbd>-<kbd>l</kbd> or execute `reset`)

I'm a bit of a beginner in terminal apps and also with Rust, so I hope this is not a too stupid question, but the complex signal handling example does not seem to provide any information about that.

**Comment by vorner** [comment]
Well, the example calls `break` in the termination signals branch, which breaks out of the loop:

```rust
            term_sig => { // These are all the ones left
                eprintln!("Terminating");
                assert!(TERM_SIGNALS.contains(&term_sig));
                break; // <==== This is the important line
            }
```

That would exit the loop and do the shutdown as part of `app.wait_for_stop` (somehow ask the rest of the application to terminate). Doesn't that work properly?

Alternatively, one could do other things, like:
* Place the signal handling into other than the main thread. These are waited for when the main thread exits.
* [Close](https://docs.rs/signal-hook/0.3.8/signal_hook/iterator/backend/struct.Handle.html#method.close) the signals iterator

I think there's nothing wrong with the library, or anything that would require any action here, so I'll close the issue. But if I have misunderstood you and there's indeed something wrong with either the library or the example, please reopen (in such case, a full reproducer/failing test showing what is wrong would be best for explanation).

**Comment by zoechi** [comment]
Thanks a lot for having a look.

This example code works fine if there actually is a signal, but without a signal the `break;` is never reached.
What's still not clear to me is how to end the normally after all threads completed and only this `for info in &mut signals {` line keeps waiting for a signal.

I found a mention (for C) that an app could send a signal to itself using raise, but haven't found anything like that in Rust so I thought it's probably not too common and not the first go-to approach.

**Comment by vorner** [comment]
You can use raise (it's actually wrapped into safe API as part of signal-hook). Or you can call the close, as mentioned above.

The example kind of assumes the application runs „forever“ and that it terminates only by a signal, yes. You could use the method of signal handling being somewhere in a background thread that doesn't wait for them.

**Comment by zoechi** [comment]
`close()` worked perfectly.
I was too confused from all the searching and experimenting to understand your suggestion at first.
Thanks a lot!!
