### ISSUE TITLE
signal-hook-tokio: Functionality available inside signal handlers?

### ISSUE THREAD

**Issue by glts** [vorner/signal-hook#116]
The documentation of signal-hook contains a few warnings about usage. For example, it says:

> […] the set of functions one may call inside a signal handler is limited to very few of them. […] mutexes (or other locking mechanisms) and memory allocation and deallocation is not allowed

Does this apply to signal-hook-tokio, too? The doc does not have such a warning. The example even shows reloading configuration and reopening log files inside the signal handler.

Are there some guidelines on Rust functionality safely available in a signal-hook-tokio signal handler? Thank you!

**Comment by vorner** [comment]
Let me close this one, then.
