### ISSUE TITLE
Queued real time signals get lost

### ISSUE THREAD

**Issue by richardweinberger** [vorner/signal-hook#122]
Real time signals are queueable, if the application is busy with handling a signal and another one arrives, the kernel queues it and delivers it after the handler is done.
My Linux application makes use of SIGRT_8.
When the signal is send N times to the application, I see my rust handler only a few times executed.

A down stripped variant of my application is:
```
use signal_hook::iterator::Signals;
use std::{thread, time::Duration};

fn main() {
    let sigrt8 = 40; // SIGRTMIN + 8 on Linux

    let mut signals = Signals::new(&[sigrt8]).unwrap();

    thread::spawn(move || {
        for sig in signals.forever() {
            println!("Received signal {:?}", sig);
            thread::sleep(Duration::from_secs(1));
        }
    });

    loop {
        thread::sleep(Duration::from_secs(1));
    }
}
```

When I run on a different shell:
```
for i in `seq 1 50` ; do kill -40 `pidof sigtest` ; done
```

I'd expect to see 50 lines "Received signal 40" printed. But usually I get only 2 or 3.

**Comment by vorner** [comment]
Hello

This is a known limitation of `Signals`. It's even hinted a bit on the front page of documentation (see the last bullet point of Limitations). So if you really need to preserve all instances, it's probably not the right tool for the job.

To provide a bit more details, `Signals` is just a wake-up pipe and bunch of flags, put into somewhat convenient wrapping. I'm not against suggestions how to improve on that, but I'm skeptical about it ‒ a signal handler can't block until someone consumes them and it can't allocate.

I see two paths you could take.

* Do the handling inside the signal handler (you could still use signal-hook-registry to provide the multiplexing means). That's a bit of very careful unsafe, though.
* If you're fine with having a fixed backlog capacity, you could build something with https://docs.rs/signal-hook/0.3.10/signal_hook/low_level/channel/struct.Channel.html. You still would have to do a bit of unsafe (the sending part goes inside the handler), but there'd be less of it.

Or, if you know of some other patter that would be useful for that scenario that's commonly used, it could be implemented, provided its usage could be made safe.

**Comment by richardweinberger** [comment]
Thanks for your prompt answer!

> This is a known limitation of `Signals`. It's even hinted a bit on the front page of documentation (see the last bullet point of Limitations). So if you really need to preserve all instances, it's probably not the right tool for the job.

Ah, that one:
> Many of the patterns here can collate multiple instances of the same signal into fewer instances, if the application doesn’t consume them fast enough. This is consistent with what the kernel does if the application doesn’t keep up with them, so it is something one needs to deal with anyway.

That's actually not entirely true. It is for normal signals but not for real time signals.
real time signals do queue if the application handles them slower than new signals arrive.
And no signals are lost or collated.

This tiny C program does more or less that my rust program does but it is not losing signals.
```
#include <stdio.h>
#include <signal.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>

static void handler(int sig, siginfo_t *si, void *d)
{
        printf("got signal: %d\n", sig);
        sleep(1);
}

int main(void)
{
        struct sigaction sa;

        memset(&sa, 0x00, sizeof(sa));

        sa.sa_sigaction = handler;
        sa.sa_flags = SA_RESTART|SA_SIGINFO;

        assert(sigaction(40, &sa, NULL) == 0);

        for (;;) {
                pause();
        }

        return 0;
}
```

If you observe /proc/PID/status you'll see that the signal queue fills and is slowly emptied.
And if the queue is full, the sender will get an error such that it can know about a full queue on
the receiving side.

> To provide a bit more details, `Signals` is just a wake-up pipe and bunch of flags, put into somewhat convenient wrapping. I'm not against suggestions how to improve on that, but I'm skeptical about it ‒ a signal handler can't block until someone consumes them and it can't allocate.

Okay. This is explains why real time signals don't work properly.

> I see two paths you could take.
> 
>     * Do the handling inside the signal handler (you could still use signal-hook-registry to provide the multiplexing means). That's a bit of very careful unsafe, though.
> 
>     * If you're fine with having a fixed backlog capacity, you could build something with https://docs.rs/signal-hook/0.3.10/signal_hook/low_level/channel/struct.Channel.html. You still would have to do a bit of unsafe (the sending part goes inside the handler), but there'd be less of it.
> 
> 
> Or, if you know of some other patter that would be useful for that scenario that's commonly used, it could be implemented, provided its usage could be made safe.

I need to dig into the source first to think about it. But I begin to realize that signal-hook is not the right thing for me.
Maybe I'll just use the signalfd syscall.

**Comment by vorner** [comment]
> That's actually not entirely true.

Indeed, the part about the kernel is not, and I should fix that. But the part that this library collates signals, unfortunately, is.

> This tiny C program does more or less that my rust program does but it is not losing signals.

I believe that C program contains UB (`printf` is not async-signal-safe, so it can't be part of a signal handler). This is where the Rust program differs ‒ it postpones handling of the signals until later, which completely side-steps the problem of async-signal-safety. But it also introduces the collation.

If you wanted some rough equivalent of your C program, you could do something like:

```rust
fn handler(info: &siginfo_t) {
    // ...whatever...
}

unsafe { signal_hook_registry::register_sigaction(40, handler) }
```

But the signal-hook on top of signal-hook-registry was probably designed more for the „common“ signals. The „realtime“ part of the realtime signals sound like one would want to act on them right inside the handler and not postpone them, which is very much the opposite of what one wants with eg. `SIGTERM`.

**Comment by richardweinberger** [comment]
> > That's actually not entirely true.
> 
> Indeed, the part about the kernel is not, and I should fix that. But the part that this library collates signals, unfortunately, is.
> 
> > This tiny C program does more or less that my rust program does but it is not losing signals.
> 
> I believe that C program contains UB (`printf` is not async-signal-safe, so it can't be part of a signal handler). This is where the Rust program differs ‒ it postpones handling of the signals until later, which completely side-steps the problem of async-signal-safety. But it also introduces the collation.

My C program is just an example...
And since no other part of the program is using stdio...

> 
> If you wanted some rough equivalent of your C program, you could do something like:
> 
> ```rust
> fn handler(info: &siginfo_t) {
>     // ...whatever...
> }
> 
> unsafe { signal_hook_registry::register_sigaction(40, handler) }
> ```
> 
> But the signal-hook on top of signal-hook-registry was probably designed more for the „common“ signals. The „realtime“ part of the realtime signals sound like one would want to act on them right inside the handler and not postpone them, which is very much the opposite of what one wants with eg. `SIGTERM`.

Thanks a lot! I'll give it a try soon. :-)

**Comment by richardweinberger** [comment]
It turned out that using libc::signalfd is the best approach for me. That way may application can handle real time signals in a safe way. :-)
