### ISSUE TITLE
Purpose of ‘fuse’ in signal-hook-tokio example code?

### ISSUE THREAD

**Issue by glts** [vorner/signal-hook#128]
I am revisiting a piece of code similar to the `handle_signals` example at https://docs.rs/signal-hook-tokio.

In the example, the `Signals` stream is fused, but I can’t see why. The fused stream is only used in `while let Some(signal) = signals.next().await`. As far as I can see, the first `None` in the stream would exit the loop.

Is `fuse` really necessary for correctness in the example, or could I delete this line from my code?

**Comment by vorner** [comment]
I have to admit, I'm not sure. I see no particular reason myself. What I suspect is that similar piece of example got copy-pasted and modified around a bit and it got left in there.

Furthermore, it seems it should act safe if used even past its end: https://docs.rs/signal-hook-tokio/latest/src/signal_hook_tokio/lib.rs.html#154.

I should probably have a closer look at this code and improve it a bit.

**Comment by vorner** [comment]
I've released a version with the fuse removed.

**Comment by glts** [comment]
Thank you
