### ISSUE TITLE
Include LICENSE files into signal-hook-registry

### ISSUE THREAD

**Issue by ignatenkobrain** [vorner/signal-hook#13]
Otherwise crates.io tarball doesn't contain them.

You can use simple symlink to do that.

Thanks!

**Comment by vorner** [comment]
I can add them, though is it really necessary to have them in the tarball? It already contains the Cargo.toml which states the license, link to the repository that contains them, readme that links them on their home pages. So, is there really an added value?

I'm not a lawyer, so it might actually be mandated by something, or there's a use case I don't see ‒ so I would just like to understand.

Thank you

**Comment by ignatenkobrain** [comment]
IIUC, Apache-2.0 license say that license text should be shipped with sources... And while it is on github, it is not on crates.io tarball which is used for packaging for distributions.

**Comment by vorner** [comment]
OK, I'll do, probably tomorrow.

**Comment by ignatenkobrain** [comment]
Thanks! I'll probably just send PR right away.

**Comment by vorner** [comment]
OK, I've released a new patch version with them.
