### ISSUE TITLE
Use rustix instead of libc

### ISSUE THREAD

**Issue by notgull** [vorner/signal-hook#142]
`rustix` is a Rust-idiomatic interface to various system calls. Aside from being more idiomatic than normal system calls, it's claim to fame is that it bypasses `libc` to use direct system calls on Linux. In some cases, the system calls can be directly inlined into their calling functions.

`rustix` recently merged support for signal handling. It would be nice if this crate used those functions instead of `libc`'s, in order to optimize these functions.

**Comment by vorner** [comment]
Hello

Does it also work on all the other platforms signal-hook supports? What is its minimal rust version? Does it also provide functions for all the rest?

**Comment by notgull** [comment]
> Does it also work on all the other platforms signal-hook supports?

It doesn't work on Windows, but we could just keep using `libc` there... or, preferably, the actually underlying Win32 calls, but that's another issue.

> What is its minimal rust version?

It's minimal Rust version is tied to Debian Stable; as of the time of writing, it's 1.48. This should be low enough for most realistic use cases.

> Does it also provide functions for all the rest?

For now, it provides all of the functions needed to reimplement `signal-hook-registry`. I'm not sure if it provides things like `raise` for `signal-hook`, but we could just implement it in the registry crate first.

**Comment by notgull** [comment]
Sounds good (and, from discussion on Rustix, it may be a bad idea to do signal handling outside of the libc anyways).

However, it's my understanding that, in the Rust community, bumping the minimum supported Rust version corresponds with a minor version bump rather than a major one. I forget what the exact reasoning for this is, but a bump in MSRV doesn't also mean a bump in the major version.

In addition, I doubt that anyone is using rustc 1.26, a version of Rust that is almost five years old at this point. Even Debian Stable, famed for using old versions is software, uses rustc 1.48.

**Comment by notgull** [comment]
After discussion with the rustix maintainers, this is probably a bad idea. signal handling should be done through the libc

**Comment by polarathene** [comment]
> After discussion with the rustix maintainers, this is probably a bad idea. signal handling should be done through the libc

Adding for context to anyone arriving here, but Rustix 1.0 has since been released (2025), and a crate `c-scape` implemented the `sigaction()` libc call, which a higher level crate like `eyra` could potentially address the wishlist described here (_handled at application `Cargo.toml` rather than anything a library needs to be concerned about AFAIK_).

More details at the rustix discussion: https://github.com/bytecodealliance/rustix/issues/628#issuecomment-4678305096
