### ISSUE TITLE
Use vectored exception handlers on Windows

### ISSUE THREAD

**Issue by notgull** [vorner/signal-hook#143]
`libc::signal()` on Windows is powered by Win32 exceptions under the hood. You can use the [`AddVectoredExceptionHandler`](https://learn.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-addvectoredexceptionhandler) function to act on signals instead without going through the CRT.

**Comment by vorner** [comment]
Err, let me put it this way. I don't have any Windows machine around here. The minimal support there was mostly contributed by someone (git might know who exactly) and I've only kept it working using CI.

In that sense, if you can send a pull request doing it that way (which I assume is more "native" way for Windows and with less amount of drawbacks), it would be appreciated. Even more if you could have a look at other parts that aren't available on Windows and are missing, or become something like a maintainer for that platform 😈.

**Comment by notgull** [comment]
On further research, this may be a bad idea
