### ISSUE TITLE
API for masking signals

### ISSUE THREAD

**Issue by diwic** [vorner/signal-hook#2]
If you have a program with real-time requirements, e g if you're running low-latency audio, you're having one thread of critical priority which does this and other threads at normal priority. You would probably prefer if signals (that the program handles) are happening in some other thread than the real-time critical one. 

It would be nice if there was a safe abstraction to masking signals in specific thread(s) for this reason.

**Comment by vorner** [comment]
OK, I've just released a new version that links to the nix crate in documentation.

Feel free to reopen if there's a reason to have it in this crate too (eg. it should in some more direct way interact with the API this crate offers).
