### ISSUE TITLE
Tokio 0.2 support

### ISSUE THREAD

**Issue by vorner** [vorner/signal-hook#24]
Tokio is probably close to releasing its version 0.2 and this crate should be ready for it. Maybe it is even possible to do it in a way that one feature turns on support for tokio 0.1, while another support for tokio 0.2.

The implementation needs to be against the alpha releases for now, so it probably should stay in a branch for now, to try it out, but this can be ready for just setting the right dependency and releasing.

Note that supporting async-std is currently impossible, as there's no way to plug arbitrary file descriptors into it right now.

**Comment by jjakobh** [comment]
I am currently trying to do this and it compiles but my tests fail with
`called Result::unwrap() on an Err value: Custom { kind: Other, error: "no current reactor" }`
for 
```rust
let mut runtime = Runtime::new().unwrap();
...
runtime.block_on(...)
```
and ` 'default Tokio reactor already set for execution context`
for
```rust
let reactor = tokio_net::driver::Reactor::new().unwrap();
let handle = reactor.handle();
let _guard = tokio_net::driver::set_default(&handle);
let mut runtime = Runtime::new().unwrap();

```

Any idea why this is happening?

**Comment by vorner** [comment]
I think the first should work, if you're using runtime from the same version as the network primitives (AFAIK currently tokio doesn't yet have a migration path ready, so spawning 0.2 TcpStream or anything else onto tokio 0.1 reactor doesn't work).

The second one can't work, because Runtime also sets a reactor and these two fight each other.

Anyway, it's hard to tell from this little snippet. If you could maybe share the whole code you have, I might be able to help more.

**Comment by jjakobh** [comment]
[This](https://github.com/jjakobh/signal-hook/tree/tokio-0.2) is my branch, the tests that fail are [tokio::repeated](https://github.com/jjakobh/signal-hook/blob/tokio-0.2/tests/tokio.rs#L29) and [tokio::delayed](https://github.com/jjakobh/signal-hook/blob/tokio-0.2/tests/tokio.rs#L51), and the relevant Tokio stuff is [here](https://github.com/jjakobh/signal-hook/blob/tokio-0.2/src/iterator.rs#L541).

`rg tokio Cargo.lock` shows that there is only `tokio 0.2-alpha.6` (and `tokio-timer 0.3.0-alpha.6`) in the dependency tree, so AFAICT there shouldn't be any conflicts.

**Comment by vorner** [comment]
I've discovered the problem. The `into_async` is the one that fails. The `Registration` (as is part of `Async`) could be called from outside the context of the reactor in previous versions of tokio. This is no longer the case ‒ I'm not sure if this is on purpose or by accident. Anyway, the `registration.register_with` can be moved into the `poll_next`, just before `poll_read_ready` (it's fine it'll be called repeatedly).

It seems there are some other problems, but they are not tokio related I'd say.

**Comment by jjakobh** [comment]
should the `handle` be stored inside the `Async`?
The problem is that `into_async_with_handle` then would have to take the handle by value, or should it be 
```rust
pub fn into_async_with_handle(self, handle: &Handle) -> Result<Async, Error> {
    Async::new(self, handle.clone())
}
```

**Comment by jjakobh** [comment]
anyway, those are the errors now:
```
---- tests::repeated stdout ----
thread 'tests::repeated' panicked at 'assertion failed: `(left == right)`
  left: `29`,
 right: `30`', tests/tokio.rs:37:17

---- tests::delayed stdout ----
thread 'tests::delayed' panicked at 'index out of bounds: the len is 128 but the index is 128', /rustc/c27f7568bc74c418996892028a629eed5a7f5f00/src/libcore/slice/mod.rs:2716:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
I don't think I know enough about Tokio and signal-hook to debug them myself.

**Comment by vorner** [comment]
Handle can probably be taken by value. It's cheap to clone on the caller side and it's not expected one would create thousands of signal-listening streams.

As for the off-by-one numbers, I suspect it has to do with your change of order of the lines inside poll_next ‒ originally, it first took the signal reference, then incremented the position, now it happens in the other order.

**Comment by nazar-pc** [comment]
I see there was a progress made after last message here in tokio-0.2 branch.
How far is it though?

I've just decided to use `signals.into_async().unwrap().into_future()` and found that it is incompatible with Tokio 0.2 apparently.

**Comment by vorner** [comment]
I'm thinking about actually not finishing/experimenting more with that. Tokio contains its own suppot https://docs.rs/tokio/0.2.13/tokio/signal/unix/fn.signal.html, it is built on top of signal-hook-registry. So there's not much motivation.

Do you have any use case not covered by that?

**Comment by nazar-pc** [comment]
Didn't try it before, but it probably does. I'm not doing anything fancy.

**Comment by vorner** [comment]
I think this will eventually get outdated by #39.

**Comment by tfkhim** [comment]
I think we can close this one with the merge of #51.

**Comment by vorner** [comment]
Technically, we got version 0.3 there 😇. But yes, you're right. I'll keep it open just until I do the promised release.

**Comment by vorner** [comment]
OK, it's been released a minute ago :-). Thanks to everyone involved.
