### ISSUE TITLE
Suggestion: for `pipe::` write the signal number to the pipe

### ISSUE THREAD

**Issue by johnmarkwayve** [vorner/signal-hook#36]
It would be nice to have a version of the `pipe::` module which indicates which signal was triggered by writing the corresponding `i32` constant to the pipe, giving users an elegant way to identify which signal was sent and only use one pipe for all signals.

**Comment by vorner** [comment]
This is not supported for the reason it is an obvious solution that is *subtly wrong*.

As the signal handler can't block, it needs to simply give up when the read end does not keep up and it is full. So imagine you receive `SIGUSR1` 8 million times which fills the pipe. Then you receive `SIGUSR2`, but that doesn't fit. The other end wakes up and sees the 8 million `SIGUSR1`s, but the `SIGUSR2` is lost forever. If you use separate pipes, or if you use out of atomic bound flags, you lose the information of how many times each signal was received, but not a whole *kind* of signal. That is fine, as even kernel can coerce multiple same signals together.

Furthermore, as i32 is 4 bytes long, you could get a partial write ‒ get only eg. 3 bytes written and 1 thrown away. That would confuse the reader end furthermore.

Therefore, I don't like exposing an interface that is basically a footgun.

By the way, pipe+atomic flags is the thing that actually happens inside the `iterator`, if you want a ready-made solution.
