### ISSUE TITLE
The iterator module could block in the signal handler

### ISSUE THREAD

**Issue by tfkhim** [vorner/signal-hook#38]
The iterator module uses the pipe::wake method to send some data to the write end of the UnixStream. Before commit 656a1349816eb120a40064a8142cd84a7d5f00e9 the wake method used the send method with the MSG_DONTWAIT flag. The mentioned commit changed this behavior to set the fd to non blocking mode and use write in the wake method. But the iterator module doesn't use register_raw and so its write end never gets set to non blocking mode.

This is just an observation from reading the code. I didn't really test this. So correct me if I'm wrong :)

**Comment by vorner** [comment]
I think you're right. Thanks for noticing, I'll release the fix once this passes CI.

**Comment by vorner** [comment]
Published. Thanks once again.

I'll probably eventually create a test for something like that too, but I'll have to figure how to go about it.
