### ISSUE TITLE
Update `futures` version

### ISSUE THREAD

**Issue by alexkreidler** [vorner/signal-hook#40]
Right now, the `Async` struct implements an old version of `futures::stream::Stream`. This means that end-users have to use an older version of the futures crate when interacting with it.

For example, when trying to match the result of the poll, the API surface has changed: https://docs.rs/futures/0.1.29/futures/type.Poll.html vs https://docs.rs/futures/0.3.5/futures/task/enum.Poll.html

Otherwise, seems like a great library!

**Comment by vorner** [comment]
Please have a look at #39 as what the plans in that area are.

In particular:
* I want to get all async out of the „main“ crate. I don't want to do another breaking release before that to just update the library.
* I don't think it is possible without relying on a particular executor/reactor/runtime/whatever. I don't know if it is possible with async-std at all, but tokio already provides signal support. And that one does register through the signal-hook-registry.

**Comment by vorner** [comment]
Btw, I don't think there's much reason to keep this open.
