### ISSUE TITLE
`pipe::register_raw` duplicate fd code doesn't behave as intended

### ISSUE THREAD

**Issue by johnbartholomew** [vorner/signal-hook#41]
`pipe::register_raw` duplicates the given file descriptor with `dup(2)`, and has a comment saying:

```
    // We want to set the FD non-blocking. But it belongs to the caller. Therefore, we make our own
    // copy with `dup` to play on instead.
```

I think there are two problems here:

1. The O_NONBLOCK flag is a *file status* flag, not a *file descriptor* flag. This means the flag is associated with the underlying object not with the fd that you used. So the reason given in the comment doesn't actually work; subsequent accesses via the original fd will also be non-blocking. I'm afraid I don't have a truly canonical reference (it's probably somewhere in some POSIX specification that I don't have time to find) but the GNU libc documentation about [duplicating descriptors](https://www.gnu.org/software/libc/manual/html_node/Duplicating-Descriptors.html#Duplicating-Descriptors) is pretty clear:
   > You can duplicate a file descriptor, or allocate another file descriptor that refers to the same open file as the original. Duplicate descriptors share one file position and one set of file status flags (see [File Status Flags](https://www.gnu.org/software/libc/manual/html_node/File-Status-Flags.html#File-Status-Flags)), but each has its own set of file descriptor flags (see [Descriptor Flags](https://www.gnu.org/software/libc/manual/html_node/Descriptor-Flags.html#Descriptor-Flags)).

   If you follow the [File Status Flags](https://www.gnu.org/software/libc/manual/html_node/File-Status-Flags.html#File-Status-Flags) link and from there the page about [Operating Modes](https://www.gnu.org/software/libc/manual/html_node/Operating-Modes.html#Operating-Modes) you'll see O_NONBLOCK is a file status flag, and the Descriptor Flags page says `O_CLOEXEC` is currently the *only* file descriptor flag.

2. File descriptors created with `dup(2)` start off with O_CLOEXEC *cleared* (regardless of whether the original fd had O_CLOEXEC set). I'm not an authority but I think best practice is to create all descriptors with O_CLOEXEC (if on a system that provides means to do that...) unless they are being deliberately set up to be passed to a child process. Otherwise child processes will end up with extra fds that give them access to things they shouldn't have access to. This is probably harmless in the common case that children are not malicious or extremely buggy, but still it's nicer to prevent it. `fcntl` `F_DUPFD_CLOEXEC` command can be used to duplicate a file descriptor with O_CLOEXEC set (atomically; ie, there is no point at which the new descriptor is missing the flag), or on systems that don't support `F_DUPFD_CLOEXEC` you can separately set O_CLOEXEC after `dup` (though technically there's a hole where if you fork from another thread the child will inherit the descriptor). Here is how fds are duplicated in the standard library: https://github.com/rust-lang/rust/blob/47ea6d90b073ab977cf072e2f5f46d63de532cc6/src/libstd/sys/unix/fd.rs#L223

I don't think these problems are hugely important but it would be nice to fix the O_CLOEXEC thing at least, and that should be fixable without an API change. For the O_NONBLOCK thing perhaps the documentation could be updated to warn that the underlying object will be set to non-blocking mode (I don't really see a better way there). With an API change I think it might be cleaner if register_raw takes ownership of the file descriptor, and the caller can do their own fd duplication if they want to retain direct access.

**Comment by vorner** [comment]
:sob: There are so many weird corner cases around unix API. The whole dance with `O_NONBLOCK` is there to support both sockets *and* pipes to start with, because the latter won't work with the `send` call. But great catch, thank you.

I'm planning some API breaking changes and I wonder if I should just remove the `_raw` version from public API or something like that, or mandate that the thing be a socket. I'll think about that one a bit what the best forward would be.

Anyway, you're right the close on exec would be nice to fix. Do you want to submit a PR, or should I try to get around to it some day?

**Comment by johnbartholomew** [comment]
I can make an attempt at the weekend probably. The Rust standard library implementation does some funky stuff for broad compatibility: (a) android and haiku targets don't have `F_DUPFD_CLOEXEC` defined (according to the comment anyway; I didn't try to confirm), so it just uses `F_DUPFD`, (b) it tries `fcntl(fd, F_DUPFD_CLOEXEC)` and falls back if it gets EINVAL, (c) it records that result in a static AtomicBool to skip straight to the `F_DUPFD` path next time, (d) it calls `ioctl(fd, libc::FIOCLEX)` at the end *in any case* to work around buggy kernel versions. It's a little hairy :-)

I'm not sure which of those considerations should be duplicated here - perhaps you have an opinion? I only have plain Linux here to test on myself. The simplest thing is to just use `F_DUPFD_CLOEXEC` and ignore any system that doesn't support it or doesn't implement it correctly; I expect that would be fine for the vast majority of systems, and any system that doesn't even *define* `F_DUPFD_CLOEXEC` should break at build time and can come complain then... does signal-hook support android or haiku os?

If you want the kind of broad compatibility & workarounds that std does then I don't have a better plan than just directly copying that code; it's too detailed for me to try to find an alternate way to structure it. I see Rust is dual licensed under Apache 2.0 and MIT, and the same for signal-hook, so copying may be ok? I don't know if there are specific contributor agreements or similar that would make that problematic (I am not a lawyer or other legal professional).

**Comment by vorner** [comment]
I think someone already asked for some work around for android compatibility and I believe someone mentioned some BSD in an issue, so I wouldn't like to break them. I probably should set them up as part of some CI.

On the other hand, this part of code doesn't have to be fast (we are not going to get called million of times) so the atomic bool and caching can go. I also don't think doing the cloexec on broken or really old kernels is that important.

I even wonder, if the plan is to get rid of the dup call in the 0.2 version in the coming month and this kind of signal setting up is probably going to happen at the startup of the program before any forks, doing `dup` followed by `ioctl` (and not failing on the latter one for systems that are terminally broken around ioctl) should be good enough.

**Comment by johnbartholomew** [comment]
I had missed a very important line in the existing code: `OwnedFd::set_flags` already sets `O_CLOEXEC` at the same time as setting `O_NONBLOCK`! So the code already does what you suggest, and apart from the small window between the `dup` and `fcntl` calls there is no problem after all.

If `dup` call (or even the whole `pipe::register_raw` function) will be removed in 0.2 then that covers everything in this issue.

**Comment by vorner** [comment]
Heh, I should have checked that.

Anyway, thanks for bringing the issue up. It would probably have slipped into 0.2 unnoticed otherwise, this way I'll know to do something about it, though I'm not sure what exactly.
