### ISSUE TITLE
Reexport signal constants

### ISSUE THREAD

**Issue by WiSaGaN** [vorner/signal-hook#5]
Does it make sense to reexport `libc` signal constants like `libc::SIGTERM`, and `libc::SIGINT` and others? It seems strange to not have any signal constant in a crate handling signals.

**Comment by vorner** [comment]
Maybe. There's one thing that is bugging me, though.

While the existence of signals is portable across all unix and unix-like systems, the actual set of signals can (and does) differ. I'm not entirely sure how to approach that API-wise. I probably can choose a shared commonly used subset and leave it for users to use different signals from libc as needed. But it seems somewhat incomplete.

Furthermore, if I ever start supporting systems that have non-unix signals, I'm not sure what will happen with the constants then. But I'm not sure if that is happening any time soon.

Also, I don't really like reexports much personally, but it probably makes sense in this scenario.

**Comment by WiSaGaN** [comment]
I asked because we already have this:
```
pub const FORBIDDEN: &[c_int] = &[libc::SIGKILL, libc::SIGSTOP, libc::SIGILL, libc::SIGFPE, libc::SIGSEGV]
```
But nevermind.

**Comment by birkenfeld** [comment]
> but it probably makes sense in this scenario.

Can we then reopen this please? It's really unfortunate to have to import `libc` as well...

**Comment by vorner** [comment]
Done some time ago and forgot to close this.
