### ISSUE TITLE
signal_hook_registry reexports break rustdoc links

### ISSUE THREAD

**Issue by chrisduerr** [vorner/signal-hook#64]
Since `signal_hook` reexports some things from `signal_hook_registry`, it also takes in all its documentation. However the structure for `signal_hook` is different. This means links like `unregister` in https://docs.rs/signal-hook/0.2.1/signal_hook/cleanup/fn.unregister_signal.html point to pages that do not exist.

I was just going to send a PR to fix this, however I'm not even entirely sure how to best resolve this issue. I believe it would probably be possible to create an absolute link to the `signal_hook_registry` library, but that might cause some confusion for users. So maybe someone else has a better idea.

**Comment by vorner** [comment]
Thank you for reporting. Indeed, the code used the „old“ way of linking to things that produced links relative to URLs. I've changed them to the new auto-resolution links that are aware to code scopes, so it should now work.

I'm not sure I've discovered all the instances, I might try to find something that goes over the links and checks if the URL actually exists.
