### ISSUE TITLE
Better (more structured) documentation and layout

### ISSUE THREAD

**Issue by vorner** [vorner/signal-hook#69]
In #63 it was pointed out that finding one's way around in the library is rather hard. The reason probably is that some parts of the API simply grew over time and the docs were added, while the general vision was not described.

One needs to understand:
* Some calls are low level and very much manual (`register` vs `unregister`, SigID being just dumb ID, not a handle/token and doesn't unregister on drop).
* What APIs would one use for what.
* How signal removal is actually meant to happen.

This definitely calls for better documentation, but maybe even for some kind of re-structuring of API calls? The `register` in root, for example, is a legacy of when it lived inside the crate and wasn't a re-export from `signal-hook-register` and it might make sense to „hide“ it somewhere a bit ‒ after all, users of `signal-hook` use it because of the higher level APIs (otherwise they'd just use `signal-hook-registry`) and are unlikely to touch these.

**Comment by chrisduerr** [comment]
Just to add to this, I personally find the separation between root module and `cleanup` a bit unclear. Cleanup has methods for registring and unregistring signals, just like root. So when should which one be used?

Things like `signal_hook::cleanup::register` for example take a bit to understand (you register a signal to remove other signals? Which of the cleanup methods is used here?).

Most of the things are well documented, so you can get a picture of the library by reading through that. But ideally one shouldn't have to read and compare all functions to understand how the API is supposed to be used and composed.

The cleanup module itself also is a bit confusing. It has the functions `cleanup_signal`, `register` and `unregister_signal` for example. Of which all have the purpose of being used during "cleanup" (whatever that might mean? Application shutdown, or cleaning up signals?), but they all are a bit different in how exactly they do cleanup (instruct cleanup vs actually cleaning up). Then there's `unregister` in root, which does the exact same thing as some methods in `cleanup` and is also definitely used for cleaning up signals, but doesn't sit in the `cleanup` module.

Generally I'm not sure the `cleanup` module sheds any more light on the API. It seems more like an artificial separation that doesn't have a clean separation.

**Comment by vorner** [comment]
I think this got improved in the just released 0.3 ‒ hopefully the modules make some more sense, low level stuff like `register` is now in a submodule, not in the root and there's an extensive example just at the root of the documentation. I'll close this as I don't have any more specific ideas.
