### ISSUE TITLE
Receiving one signal blocks others

### ISSUE THREAD

**Issue by Timmmm** [vorner/signal-hook#7]
I have this code in one of my programs:

	// Create a channel to receive signals.
	let (signal_s, signal_r) = channel::bounded(100);

	// Receive SIGWINCH on that channel.
	let signals = signal_hook::iterator::Signals::new(&[libc::SIGWINCH])?;
	thread::spawn(move || {
		for signal in signals.forever() {
			signal_s.send(signal);
		}
	});

It works for receiving `SIGWINCH`, but unfortunately it breaks Ctrl-C, which now does nothing. Is that expected?

**Comment by vorner** [comment]
It is not expected, but I couldn't reproduce it. I tried both with registering ctrl-C and leaving it to the default, and both does what it should:

```rust
extern crate libc;
extern crate signal_hook;

use std::sync::mpsc::channel;
use std::thread;
use std::time::Duration;

fn main() -> Result<(), std::io::Error> {
    // Create a channel to receive signals.
    let (signal_s, signal_r) = channel();

    // Receive SIGWINCH on that channel.
    let signals = signal_hook::iterator::Signals::new(&[libc::SIGWINCH])?;
    thread::spawn(move || {
        for signal in signals.forever() {
            signal_s.send(signal).unwrap();
        }
    });

    thread::sleep(Duration::from_secs(3600));

    /*
    for sig in signal_hook::iterator::Signals::new(&[libc::SIGTERM, libc::SIGQUIT, libc::SIGINT])?.forever() {
        println!("Sig: {}", sig);
    }
    */
    Ok(())
}
```

Can you tell me more about your code? What is the channel you use? What OS? Is the code available somewhere so I could directly try it?

Thank you

**Comment by Timmmm** [comment]
Ah my mistake - it actually happens if I don't try to intercept `SIGWINCH` too - must be something to do with using the terminal's alternate screen or something. I thought it worked before I added `SIGWINCH` but apparently not.

Sorry for wasting your time!

**Comment by Timmmm** [comment]
Ah apparently Ctrl-C doesn't work like normal when you are in raw mode:

https://stackoverflow.com/questions/43716048/capture-ctrlc-sigint-when-terminal-is-in-raw-mode

**Comment by Timmmm** [comment]
And apparently raw mode is [not what I thought it was](https://en.wikipedia.org/wiki/Terminal_mode). :-/
